// Portable ai-chat types live in @rinciku/domain/ai-chat (shared by web + mobile).
export type {
  Conversation,
  ConversationListItem,
  ChatMessageRow,
  ChatMessageRowWithImage,
  ChatItem,
  TextBlock,
  ImageBlock,
  ToolUseBlock,
  ToolResultBlock,
  ContentBlock,
  MessageParam,
  ToolDef,
  ToolChoice,
  ChatResponse,
  ProposalKind,
  DocType,
  ProposedTransaction,
  PendingAttachment,
  ChangeAction,
  ChangeEntity,
  ChangeTarget,
  ChangeTargetRecord,
  ProposedChange,
  ExportKind,
  ExportFormat,
  ExportStats,
  ExportFile,
  ProposedExport,
} from '@rinciku/domain/ai-chat';
