-- HAND-MAINTAINED — not generated by `supabase db diff`. The diff engine
-- cannot emit `revoke` or `alter default privileges` statements, so the
-- API-role privilege hardening declared in supabase/schemas/95_grants.sql
-- would never reach a generated migration. This file is its applied twin:
-- keep the two in sync.
--
-- Why: the platform's default ACL grants truncate/references/trigger/maintain
-- to anon, authenticated, and service_role on every CREATE TABLE, and the
-- initial migration additionally granted anon full DML. anon must have NO
-- table access — the app only queries as `authenticated`, and anon access
-- would make RLS the sole barrier (one forgotten `enable row level security`
-- on a future table = world-readable data). truncate is not gated by RLS, so
-- `authenticated` must not hold it either.

-- Fix the default ACLs first, so tables created by later migrations are clean.
alter default privileges in schema public
  revoke all on tables from anon;

alter default privileges in schema public
  revoke all on sequences from anon;

alter default privileges in schema public
  revoke truncate, references, trigger, maintain on tables from authenticated;

-- Strip everything already granted to anon (the initial migration granted DML
-- + platform defaults), and the non-RLS-gated privileges from authenticated.
revoke all on all tables in schema public from anon;
revoke all on all sequences in schema public from anon;
revoke truncate, references, trigger, maintain on all tables in schema public from authenticated;

-- The generated rate_limits migration cannot carry function-privilege revokes
-- either: pin check_rate_limit to the API roles that need it (anon calling it
-- is harmless — auth.uid() is null → false — but least-privilege anyway).
revoke all on function public.check_rate_limit(text, integer, integer) from public, anon;
grant execute on function public.check_rate_limit(text, integer, integer) to authenticated, service_role;
